services:
  mongodb:
    image: mongo:latest
    container_name: db_drug
    command: [--auth]
    environment:
      - MONGO_INITDB_DATABASE=db_drug
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro